"""Prove the isolated OctoPrint header fix without relaxing the G-code comparator."""
import argparse
import gzip
import hashlib
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
STAMP = b"; generated by preFlight 1.2.0 on "


def protected_content(program):
    """Historical-patch audit only: permit permutations of independent declarations.

    Every executable byte and every in-body object boundary remains exact. This
    is NOT used for candidate off/on equivalence, which uses the unchanged C++
    comparator including declaration ordering.
    """
    declarations, objects, protected = [], None, []
    header = True
    pending = None
    for line in program.splitlines(keepends=True):
        if line.startswith(STAMP):
            continue
        if line.strip() and not line.startswith(b";"):
            header = False
        if header and line.startswith(b"; printing object "):
            assert pending is None
            pending = line
        elif header and line.startswith(b"; stop printing object "):
            assert pending is not None
            assert line.removeprefix(b"; stop printing object ") == pending.removeprefix(b"; printing object ")
            declarations.append((pending, line))
            pending = None
        elif line.startswith(b"; objects_info = "):
            assert objects is None
            data = json.loads(line.removeprefix(b"; objects_info = "))
            assert set(data) == {"objects"}
            objects = sorted(data["objects"], key=lambda item: item["name"])
        else:
            protected.append(line)
    assert pending is None and len(declarations) == 2 and objects is not None
    return b"".join(protected), sorted(declarations), objects


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ("slicer", "comparator", "output"):
        parser.add_argument(f"--{name}", required=True, type=Path)
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=False)
    historical = []
    for name in ("disabled-a", "disabled-b"):
        data = gzip.decompress((ROOT / "tests/regressions/object-declarations" / f"{name}.gcode.gz").read_bytes())
        path = args.output / f"{name}.gcode"
        path.write_bytes(data)
        historical.append(path)
    assert historical[0].read_bytes() != historical[1].read_bytes()
    assert protected_content(historical[0].read_bytes()) == protected_content(historical[1].read_bytes())
    rejected = subprocess.run([str(args.comparator.resolve()), *map(str, historical), STAMP.decode()], capture_output=True, text=True)
    assert rejected.returncode == 1, "the original disabled/disabled defect must remain visible to the comparator"
    records, outputs, reports = [], [], []
    for i in range(10):
        analysis = i % 2 == 1
        path = (args.output / f"run-{i}.gcode").resolve()
        command = [str(args.slicer.resolve()), "--predictive-analysis" if analysis else "--export-gcode",
                   "--output", str(path), "--load", str(ROOT / "tests/predictive/jobs/base.ini"),
                   "--load", str(ROOT / "tests/predictive/jobs/multi_object.ini"),
                   str(ROOT / "tests/predictive/jobs/multi_object.amf")]
        with path.with_suffix(".log").open("wb") as log:
            subprocess.run(command, stdout=log, stderr=subprocess.STDOUT, check=True)
        assert protected_content(path.read_bytes()) == protected_content(historical[0].read_bytes()), "change outside permitted header ordering"
        report = Path(str(path) + ".artifact.json")
        if analysis:
            reports.append(report.read_bytes())
        else:
            assert not report.exists()
        if outputs:
            result = subprocess.run([str(args.comparator.resolve()), str(outputs[0]), str(path), STAMP.decode()],
                                    capture_output=True, text=True, check=True)
            comparison = result.stdout.strip()
        else:
            comparison = "reference"
        records.append({"command": command, "comparison": comparison, "sha256": hashlib.sha256(path.read_bytes()).hexdigest()})
        outputs.append(path)
    assert all(report == reports[0] for report in reports), "analysis reports differ across runs"
    evidence = {"historical_disabled_comparison": rejected.stdout.strip(), "only_independent_header_order_changed": True,
                "analysis_reports_identical": True, "runs": records}
    (args.output / "evidence.json").write_text(json.dumps(evidence, indent=2) + "\n", encoding="utf-8")
    print("10 production exports passed: repeatability, off/on equivalence, preserved labels and executable bytes")


if __name__ == "__main__":
    main()
